/* =====================================================
   Historical CLV:
   Historical CLV is defined as the cumulative revenue
   generated by each customer during the observation
   period (December 2009 – December 2011).
   It does not estimate future customer value.
   =====================================================*/
   
-- Historical CLV Summary
-- Result: Average CLV = 2916.71, Min CLV = 2.95 and Max CLV = 580987.04
SELECT
	ROUND(AVG(total_revenue),2) AS avg_clv,
    MIN(total_revenue) AS min_clv,
    MAX(total_revenue) AS max_clv
FROM base_customers;

-- Median historical CLV
-- Result: 856.02
WITH rn AS(
	SELECT
		customer_id,
		total_revenue,
		ROW_NUMBER() OVER(ORDER BY total_revenue) AS row_num,
		COUNT(*) OVER() AS total_rows
	FROM base_customers
	)
SELECT
	ROUND(AVG(total_revenue),2) AS median
FROM rn
WHERE row_num IN(FLOOR((total_rows+1)/2),FLOOR((total_rows+2)/2));

-- Historical CLV distribution
SELECT
	CASE
		WHEN total_revenue < 800 THEN 'Low'
        WHEN total_revenue < 3000 THEN 'Medium'
        WHEN total_revenue < 100000 THEN 'High'
        ELSE 'Vip'
	END AS Segment,
    COUNT(*) AS Customers
FROM base_customers
GROUP BY Segment;

-- Top VIP Customers
WITH analysis AS(
	SELECT *,
		DATEDIFF((SELECT MAX(order_date) FROM base_orders),last_order_date) AS days_since_last_purchase,
		DATEDIFF((SELECT MAX(order_date) FROM base_orders),first_order_date) AS days_since_first_purchase
	FROM base_customers
	),
rfm AS(
	SELECT 
		*,
		NTILE(5) OVER(ORDER BY days_since_last_purchase DESC) AS R,
		NTILE(5) OVER(ORDER BY total_orders) AS F,
		NTILE(5) OVER(ORDER BY total_revenue) AS M
	FROM analysis
	)
SELECT
	customer_id,
    total_revenue,
    R, F, M
FROM rfm
WHERE total_revenue >=100000;